exclude: ".venv"
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude_types: ["qml", "ts"]
  - id: fix-encoding-pragma
    args: [--remove]
    exclude_types: ["qml", "ts"]
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude_types: ["qml", "ts"]

# Using this mirror uses mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.11.0
  hooks:
  - id: black
    exclude_types: [directory,]
    require_serial: true
    types: [file, python]

- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
    - id: isort
      types: [file, python]
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/pycqa/pylint
  rev: v4.0.3
  hooks:
    - id: pylint
      types: [python]
      args: ["--fail-under=7"]
