flowchart TB
    A[<a href="https://elan-gis.org/fr/preparation.html#routes">Routes et bâtiments</a>]
    B[<a href="https://elan-gis.org/fr/preparation.html#population">Population</a>]
    C[Projection]:::class1
    D[<a href="https://elan-gis.org/fr/scenario_prb1.html#reseau">Réseau</a>]:::class3
    B:::class3 --centroïdes--> C --centroïdes projetés--> D
    B --centroïdes--> D
    F@{ shape: circle, label: <a href="https://elan-gis.org/fr/preparation.html#entrees-reseau">MNT</a> }
    G@{ shape: circle, label: <a href="https://elan-gis.org/fr/preparation.html#entrees-reseau">exutoires</a> }
    H@{ shape: circle, label: <a href="https://elan-gis.org/fr/preparation.html#entrees-reseau">routes</a> }
    I@{ shape: circle, label: <a href="https://elan-gis.org/fr/preparation.html#entrees-reseau">bâtiments</a> }
    A:::class1 --polygones--> I:::class0 --> B
    A --> H:::class0 --> D
    F:::class0 --> D
    G:::class0 --> D
    J[<a href="https://elan-gis.org/fr/scenario_prb1.html#visualisation-profils">Profils de canalisations</a>]:::class1
    K[<a href="https://elan-gis.org/fr/scenario_prb1.html#procedes">Procédés</a>]:::class3
    L[<a href="https://elan-gis.org/fr/scenario_prb1.html#creer-scenario">Créer un scénario</a>]:::class3
    M[Plots]:::class3
    N@{ shape: circle, label: <a href="https://elan-gis.org/fr/scenario_prb1.html#sorties-reseau">réseau pré <br/> dimensionné</a> }
    D --> N:::class2
    N --canalisations--> J
    N --STEU--> Q:::class0 --> K
    K --filières--> M 
    N --> L
    O@{ shape: framed-circle, label: "Stop" }
    P@{ shape: hex, label: <a href="https://elan-gis.org/fr/scenario_prb1.html#selection">Sélection</a> }
    M --> P:::class2 --> L
    L -- objet scénario --> O
    Q@{ shape: hex, label: <a href="https://elan-gis.org/fr/scenario_prb1.html#set-concentrations">Précision C_in <br/> et C_obj</a> }
    classDef class0 fill:#E6E6FA, stroke:#9932CC
    classDef class1 fill:#FFE4B5, stroke:#FFE4B5
    classDef class2 fill:#F0FFF0, stroke:#2E8B57
    classDef class3 fill:#FFF5EE, stroke:#FF8C00
